
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.text-to-speech]
verify_jwt = false

[functions.generate-background-music]
verify_jwt = false
